{{- if has "gpt-oss" .Values.components }}
---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: gpt-oss-api
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
    component: gpt-oss
spec:
  title: "GPT OSS API"
  description: "GPT OSS API spec"
  openApiSpec:
    url: https://raw.githubusercontent.com/traefik-workshops/traefik-airlines/refs/heads/main/oas/openapi.yaml
    override:
      servers:
        - url: {{ include "chats.gptOss.apiUrl" . }}
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gpt-oss-route
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
    component: gpt-oss
  annotations:
    hub.traefik.io/api: gpt-oss-api
spec:
  entryPoints:
    {{- range .Values.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - kind: Rule
      match: {{ include "chats.gptOss.hostMatch" . }}
      services:
        - name: gpt-oss
          namespace: chats
          port: 443
          scheme: https
          passHostHeader: false
      observability:
        traceVerbosity: detailed
    - kind: Rule
      match: {{ include "chats.gptOss.hostMatchCompletions" . }}
      services:
        - name: gpt-oss
          namespace: chats
          port: 443
          scheme: https
          passHostHeader: false
      observability:
        traceVerbosity: detailed
      middlewares:
        - name: gpt-oss-cc
        {{- if .Values.middlewares.semanticCache.enabled }}
        - name: cc-semantic-cache
        {{- end }}
        {{- if .Values.middlewares.contentGuard.enabled }}
        - name: cc-content-guard
        {{- end }}
        {{- if .Values.middlewares.llmGuards.enabled }}
        {{- if .Values.middlewares.llmGuards.useHubChain }}
        - name: cc-llmguard-chain
        {{- else }}
        {{- if .Values.middlewares.llmGuards.topicControlGuard.enabled }}
        - name: cc-topic-control-guard
        {{- end }}
        {{- if .Values.middlewares.llmGuards.contentSafetyGuard.enabled }}
        - name: cc-content-safety-guard
        {{- end }}
        {{- if .Values.middlewares.llmGuards.jailbreakDetectionGuard.enabled }}
        - name: cc-jailbreak-detection-guard
        {{- end }}
        {{- end }}
        {{- end }}
{{- end }}
