{{- if .Values.chat.llms.openai.enabled }}
---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: openai-api
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
    component: openai
spec:
  title: "OpenAI API"
  description: "OpenAI API spec"
  openApiSpec:
    url: https://raw.githubusercontent.com/traefik-workshops/traefik-airlines/refs/heads/main/oas/openapi.yaml
    override:
      servers:
        - url: https://openai.{{ .Values.domain }} 
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openai-route
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
    component: openai
  annotations:
    hub.traefik.io/api: openai-api
spec:
  entryPoints:
    {{- range .Values.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - kind: Rule
      match: Host(`openai.{{ .Values.domain }}`)
      services:
        - name: openai
          namespace: airlines
          port: 443
          scheme: https
          passHostHeader: false
      observability:
        traceVerbosity: detailed
      middlewares:
        - name: cc-authtoken
    - kind: Rule
      match: Host(`openai.{{ .Values.domain }}`) && PathPrefix(`/v1/chat/completions`)
      services:
        - name: openai
          namespace: airlines
          port: 443
          scheme: https
          passHostHeader: false
      observability:
        traceVerbosity: detailed
      middlewares:
        - name: openai-cc
        - name: cc-authtoken
        {{- if .Values.chat.semantic_cache.enabled }}
        - name: cc-semantic-cache
        {{- end }}
        {{- if .Values.chat.content_guard.enabled }}
        - name: cc-content-guard
        {{- end }}
        {{- if .Values.chat.guards.enabled }}
        {{- if .Values.chat.guards.parallel }}
        - name: cc-llmguard-chain
        {{- else }}
        {{- if .Values.chat.guards.topic_control.enabled }}
        - name: cc-topic-control-guard
        {{- end }}
        {{- if .Values.chat.guards.content_safety.enabled }}
        - name: cc-content-safety-guard
        {{- end }}
        {{- if .Values.chat.guards.jailbreak_detection.enabled }}
        - name: cc-jailbreak-detection-guard
        {{- end }}
        {{- if .Values.chat.guards.granite_guardian.enabled }}
        - name: cc-granite-guard
        {{- end }}
        {{- end }}
        {{- end }}
{{- end }}
