---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: ancillaries-api
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
spec:
  title: "Ancillaries API"
  description: "Management of ancillary services like meals and upgrades"
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: {{ include "airlines.ancillaries.apiUrl" . }}
  cors:
    allowHeadersList: ["Authorization", "Content-Type"]
    allowOriginsList: ["*"]
    allowMethodsList: ["GET", "POST"]
    allowCredentials: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ancillaries-route
  namespace: airlines
  annotations:
    hub.traefik.io/api: ancillaries-api
spec:
  entryPoints:
    {{- range .Values.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - kind: Rule
      match: {{ include "airlines.ancillaries.hostMatch" . }}
      services:
        - name: ancillaries-app
          port: 3000
