---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAuth
metadata:
  name: jwt-auth
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
spec:
  isDefault: true
  jwt:
    appIdClaim: group
    jwksUrl: {{ include "airlines.oidc.jwksUrl" . }}
---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPortalAuth
metadata:
  name: oidc-portal-auth
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
spec:
  oidc:
    issuerUrl: {{ include "airlines.oidc.issuerUrl" . }}
    secretName: oidc-credentials
    scopes:
      - openid
      - profile
      - email
      - group
    claims:
      groups: group
      userId: sub
      email: email
      firstname: given_name
      lastname: family_name
    syncedAttributes:
      - groups
      - email
      - firstname
      - lastname
      - userId
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-credentials
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.oidc.clientId }}
  clientSecret: {{ .Values.oidc.clientSecret }}
