{{- if .Values.oidc.ticketing.clientID }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ticketing-oidc
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
spec:
  plugin:
    oidc:
      clientID: "{{ .Values.oidc.ticketing.clientID }}"
      clientSecret: "{{ .Values.oidc.ticketing.clientSecret }}"
      issuerURL: "{{ .Values.oidc.ticketing.issuerURL }}"
      redirectURI: "https://ticketing-agent.{{ .Values.domain }}/callback"
      scopes: ["openid", "profile", "email"]
      cookieName: "ticketing_oidc"
      forwardAuthHeaders:
        - "Authorization"
{{- end }}

{{- if .Values.oidc.userAssistance.clientID }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: user-assistance-oidc
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
spec:
  plugin:
    oidc:
      clientID: "{{ .Values.oidc.userAssistance.clientID }}"
      clientSecret: "{{ .Values.oidc.userAssistance.clientSecret }}"
      issuerURL: "{{ .Values.oidc.userAssistance.issuerURL }}"
      redirectURI: "https://user-assistance.{{ .Values.domain }}/callback"
      scopes: ["openid", "profile", "email"]
      cookieName: "user_assistance_oidc"
      forwardAuthHeaders:
        - "Authorization"
{{- end }}

{{- if .Values.oidc.partnerAssistance.clientID }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: partner-assistance-oidc
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
spec:
  plugin:
    oidc:
      clientID: "{{ .Values.oidc.partnerAssistance.clientID }}"
      clientSecret: "{{ .Values.oidc.partnerAssistance.clientSecret }}"
      issuerURL: "{{ .Values.oidc.partnerAssistance.issuerURL }}"
      redirectURI: "https://partner-assistance.{{ .Values.domain }}/callback"
      scopes: ["openid", "profile", "email"]
      cookieName: "partner_assistance_oidc"
      forwardAuthHeaders:
        - "Authorization"
{{- end }}
