apiVersion: v1
kind: ConfigMap
metadata:
  name: airlines-shared-code
  namespace: airlines
  labels:
    app.kubernetes.io/name: airlines-shared-code
data:
  base_service.py: |
{{ .Files.Get "services/base_service.py" | indent 4 }}
  
  requirements.txt: |
{{ .Files.Get "services/requirements.txt" | indent 4 }}
