---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: financial-aid-api
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: financial-aid

spec:
  title: "Financial Aid API"
  description: "Financial Aid API spec"
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: https://financial-aid-education.demo.aiworld.traefik.ai
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: financial-aid-route
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: financial-aid

  annotations:
    hub.traefik.io/api: financial-aid-api
spec:
  entryPoints:
    {{- range .Values.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - kind: Rule
      match: Host(`financial-aid-education.demo.aiworld.traefik.ai`)
      services:
        - name: financial-aid-app
          namespace: higher-ed
          port: 3000
          passHostHeader: false
      observability:
        traceVerbosity: detailed
      # middlewares:
      #   - name: coraza-waf-block-all

