entryPoints:
  - websecure

domain: triple-gate.traefik.ai

oidc:
  clientId: ""
  clientSecret: ""
  issuerUrl: ""
  jwksUrl: ""

tool-access:
  dashboard:
    token: ""
    group: "tools"
  users-assistance:
    token: ""
    group: "agents"
  partner-assistance:
    token: ""
    group: "agents"
  ticketing:
    token: ""
    group: "agents"
user-access:
  - name: "admin"
    id: ""
    group: "users"

replicaCount: 1

image:
  repository: ghcr.io/traefik-workshops/api-server
  tag: v0.1.0
  pullPolicy: IfNotPresent

mcpImage:
  repository: python
  tag: "3.11-slim"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
