---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: utility-api
  namespace: gov
  labels:
    {{- include "gov.labels" . | nindent 4 }}
    component: utility

spec:
  title: "Utility API"
  description: "Utility API spec"
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: {{ include "gov.utility.apiUrl" . }}
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: utility-route
  namespace: gov
  labels:
    {{- include "gov.labels" . | nindent 4 }}
    component: utility

  annotations:
    hub.traefik.io/api: utility-api
spec:
  entryPoints:
    {{- range .Values.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - kind: Rule
      match: {{ include "gov.utility.hostMatch" . }}
      services:
        - name: utility-app
          namespace: gov
          port: 3000
          passHostHeader: false
      observability:
        traceVerbosity: detailed
