---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: loyalty-api
  namespace: airlines
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
spec:
  title: "Loyalty API"
  description: "Frequent flyer program management"
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: {{ include "airlines.loyalty.apiUrl" . }}
  cors:
    allowHeadersList: ["Authorization", "Content-Type"]
    allowOriginsList: ["*"]
    allowMethodsList: ["GET", "POST", "PUT", "DELETE"]
    allowCredentials: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: loyalty-route
  namespace: airlines
  annotations:
    hub.traefik.io/api: loyalty-api
spec:
  entryPoints:
    {{- range .Values.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - kind: Rule
      match: {{ include "airlines.loyalty.hostMatch" . }}
      services:
        - name: loyalty-app
          port: 3000
